export const titles = [
  "From Insight to Action",
  "Fabric already tells us what is happening",
  "But then what?",
  "A small workflow becomes a full stack",
  "Meet Fabric Apps",
  "Fabric Apps + Rayfin",
  "You write the app. Fabric runs the platform.",
  "A report explains. An app enables action.",
  "When the workflow begins, the app begins",
  "What happened vs. what we did",
  "One event. Two experiences.",
  "The pattern repeats everywhere",
  "Start with the business model",
  "GitHub Copilot changes the build experience",
  "Idea → Code → Fabric",
  "Make the runway clear first",
  "Four questions before building",
  "Where this fits",
  "Fabric does not have to stop at insight",
];
